# Build stage
FROM node:16 AS build-stage

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ENV REACT_APP_SPRING_BOOT_SERVER_URL=https://everepl.com

RUN npm run build

# Production stage
FROM nginx:1.21.0-alpine AS production-stage

# Nginx 설정 파일 복사
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# 빌드된 파일을 Nginx의 정적 파일 디렉토리로 복사
COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
