# Build stage
FROM node:16 AS build-stage

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ENV REACT_APP_SPRING_BOOT_SERVER_URL=https://everepl.com

RUN npm run build

# Production stage
FROM nginx:1.21.0-alpine AS production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
